- start.go
- test/pub_test.go
> feat: test

- start.go
-  The `README.md` file is updated with relevant information about the app
Readme file is updated
> feat: update readme

- event/microserviceEvent.go
- new event `room_creator.updated_room` to change template id in showcase
new event `room_creator.updated_room` to update room
> feat: new event 'room_creator.change_template_id' to change template id in showcase

- event/microserviceEvent.go
- new event room_creator.created_room to create a new product virtual in showcase
> New event 'room_creator.created_room' 

- event/microserviceEvent.go
- new event for when a building is updated within the island room
- New event for when a building is updated within the island room. 
- Additionally, types for the room types are added. 
- The documentation is in the file
> feat: new event for when a building is updated within the island room

- event/microserviceEvent.go
- new event auth.deleted_user to delete related data
https://legendaryum.atlassian.net/browse/LE-1926
> LE-1969 Flujo para que al eliminar un user, se eliminen tambien sus recursos relacionados

- event/microserviceEvent.go
- update payload in room_inventory.update_vp_building_image event
-update payload in room_inventory.update_vp_building_image event
- new fields in payload: `roomType` and `userId`,  both of which are strings
> feat: update payload in room_inventory.update_vp_building_image event

- commenceSaga.go
- micro/sagaCommands.go
Added new saga update_island_room_template to update data from island rooms in room creators and showcase
Added new saga update_island_room_template to update data from island rooms in room creators and showcase
https://legendaryum.atlassian.net/browse/LE-2032
>  Added new saga update_island_room_template 

- consumeChannelMicroservice.go
`type NextStepPayload`
Is a type self explanatory
> feat: nextsteppayload

- Makefile
- consumeCallbackEvent.go
- consumeCallbackSagaCommand.go
- go.mod
- go.sum
- micro/sagaCommands.go
- start.go
- test/conf_test.go
- `zap.Logger` in Transactional
- The logger in the handler through the consumers
- `Conf` function to create a `Transactional`
- unit test con `Conf`
New functions and methods documented
> logger in the consumers and handlers, unit test of the config struct

- consumeCallbackEvent.go
- consumeCallbackSagaCommand.go
Making the logger in Handler **public**
Is not necessary
> feat: fix logger in handler

- event/microserviceEvent.go
- `legend_missions.completed_mission_reward`: new event to give the user coins for completing a mission
This event will be emitted when a user completes a mission and should be given coins as a reward
> feat: new event to give the user coins for completing a mission

- micro/sagaCommands.go
- micro missions added to available microservices list
- micro missions added to available microservices list
> feat: micro missions added to available microservices list

- event/microserviceEvent.go
- event to set a mission in progress
- event to set a mission in progress. docs in the file
> feat: event to set a mission in progress

- event/microserviceEvent.go
-   New event for logout the user in the backend infrastructure, actions like disconnect the user from the websocket connection are taken
- The event is documented
> feat: event logout user

- .github/workflows/check-dependencies.yml
- commenceSaga.go
- docker-compose.yml
- event/microserviceEvent.go
- go.mod
- go.sum
- micro/sagaCommands.go
-  Update user picture step
- Delete commence saga update social user image
All is documented
> Le 2215 update social picture

- micro/sagaCommands.go
- auth command for update picture image deleted
All is doc
> feat: auth command for update picture image deleted

- micro/sagaCommands.go
micro social media rooms added to available microservices list
micro social media rooms added to available microservices list
https://legendaryum.atlassian.net/browse/LE-2270
> LE-2270 micro social media rooms added to available microservices list

- event/microserviceEvent.go
- micro/sagaCommands.go
micro lengend-send-email added to available microservices list
Event to set a send a new email to a user
micro lengend-send-email added to available microservices list
Event to set a send a new email to a user
https://legendaryum.atlassian.net/browse/LE-2278
> LE-2278  Event to set a send a new payment email to a user

- event/microserviceEvent.go
-  Event to delete assets in batch
- The event is documented
https://legendaryum.atlassian.net/browse/LE-2287
> Event to delete assets in batch

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/check-dependencies.yml
- .github/workflows/code-quality-check.yml
- .github/workflows/new-pr-to-main.yaml
- .github/workflows/release.yml
- .golangci-gin.yml
- .goreleaser.yaml
- Makefile
- README.md
- compose.prettier.yml
- go.mod
- prettier.Dockerfile
- go version `1.23.0`
- make prettier, linting for yaml files
- it's not needed, CI tools created
> feat: update go, make prettier

- docker-compose.yml
- event/microserviceEvent.go
Email is added to 'coins.send_email' event
The email prop is added to the struct already doc
> feat:  email is added to 'coins.send_email' event

- .golangci-gin.yml
- Makefile
- commenceSaga.go
- consumeCallbackEvent.go
- consumeCallbackSagaCommand.go
- consumeChannelMicroservice.go
- createConsumers.go
- createHeaderConsumer.go
- prepare.go
- publishEvent.go
- sendToQueue.go
- start.go
- test/conf_test.go
- test/pub_test.go
- Replace global vars with props in struct `Transactional`
- No more standalone functions, all functions works as methods of  `Transactional`
All is documented
> feat:  channels and methods in struct Transactional, no more global var or standalone func

- micro/sagaCommands.go
New rankings micro in arch
All is doc
> feat: rankings micro added

- go.mod
- go.sum
- micro/sagaCommands.go
Create a new user in a transaction manner with the saga "create_user"
All is documented
> Le 2548 create user transaction

- event/microserviceEvent.go
- new event to send emails to winners when the ranking finishes
- fix in the organization of events
docs are in the respective files
> feat: new event to send emails to winners when the ranking finishes and fix in the organization of events

- Makefile
- commenceSaga.go
- prettier.Dockerfile
- publishEvent.go
- start.go
- test/pub_test.go
Independent send-channel for publish and commence-saga operations
Is documented
> feat:  independent consume/publish chan -> send channel and conn

- micro/sagaCommands.go
- publishEvent.go
New domain: blockchain
Is all documented
> feat: new blockchain domain

- event/microserviceEvent.go
- test/pub_test.go
- update `social.new_user` event payload
- update testing case for `social.new_user` event
- update `social.new_user` event payload
- docs in file
> feat: update social.new_user event payload

- event/microserviceEvent.go
- replace enum with string in the 'rewardType' field of the 'CompletedRanking' structure
- docs in file
> feat: replace enum with string in the 'rewardType' field of the 'CompletedRanking' structure

- Makefile
- commenceSaga.go
- event/microserviceEvent.go
- micro/sagaCommands.go
- feat: event replacement for sending crypto rewards via a saga
- minor improve in `test` command in the Makefile
- feat: event replacement for sending crypto rewards via a saga
- docs in the file
> feat: event replacement for sending crypto rewards via a saga

- event/microserviceEvent.go
- Add `nftBlockchainNetwork` and `nftContractAddress` to CompletedRanking interface.
- Docs in file.
> feat: add nft fields to CompletedRanking struct

- event/microserviceEvent.go
- add 'walletCryptoAsset' field in CompletedRanking struct.
- add comments for fields in CompletedRanking struct.
- docs are in file.
> feat: add 'walletCryptoAsset' field in CompletedRanking struct

- event/microserviceEvent.go
- replace LegendShowcaseProductVirtualDeleted with LegendShowcaseProductVirtualDeletedEvent
- add LegendShowcaseProductVirtualDeletedEvent in MicroserviceEventValues
- docs in file
> fix: add LegendShowcaseProductVirtualDeletedEvent in MicroserviceEventValues

- event/microserviceEvent.go
- new event 'legend_missions.new_mission_created'
- docs in file
> feat: new event 'legend_missions.new_mission_created'

- event/microserviceEvent.go
- feat: add event to notify that a user has completed a mission with crypto reward 
- docs in file
> feat: add event to notify that a user has completed a mission with crypto reward

- commenceSaga.go
- event/microserviceEvent.go
- micro/sagaCommands.go
- event replacement by a saga to transfer rewards from a crypto mission
- event replacement by a saga to transfer rewards from a crypto mission
- docs in file
> feat: event replacement by a saga to transfer rewards from a crypto mission
